"""
Compliance Evidence Report Generator.

Generates JSON and HTML evidence reports from rai-guard audit data.
HTML report is self-contained (single file) for portability.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>rai-guard Compliance Evidence Report</title>
<style>
  :root {{ --green: #16a34a; --red: #dc2626; --amber: #d97706; --blue: #2563eb; --gray: #6b7280; }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f9fafb; color: #111827; }}
  .header {{ background: #111827; color: white; padding: 2rem 3rem; }}
  .header h1 {{ font-size: 1.75rem; font-weight: 700; }}
  .header p {{ color: #9ca3af; margin-top: 0.25rem; font-size: 0.9rem; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 2rem 1.5rem; }}
  .grid-3 {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin-bottom: 2rem; }}
  .card {{ background: white; border-radius: 0.5rem; padding: 1.25rem; box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
  .card h3 {{ font-size: 0.8rem; text-transform: uppercase; letter-spacing: .05em; color: var(--gray); margin-bottom: 0.5rem; }}
  .card .value {{ font-size: 2rem; font-weight: 700; }}
  .grade-A {{ color: var(--green); }}
  .grade-B {{ color: var(--blue); }}
  .grade-C {{ color: var(--amber); }}
  .grade-D, .grade-F {{ color: var(--red); }}
  .section {{ background: white; border-radius: 0.5rem; padding: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,.1); margin-bottom: 1.5rem; }}
  .section h2 {{ font-size: 1.1rem; font-weight: 600; margin-bottom: 1rem; border-bottom: 1px solid #e5e7eb; padding-bottom: 0.75rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.875rem; }}
  th {{ text-align: left; padding: 0.5rem 0.75rem; background: #f3f4f6; color: var(--gray); font-weight: 600; text-transform: uppercase; font-size: 0.75rem; letter-spacing: .05em; }}
  td {{ padding: 0.6rem 0.75rem; border-bottom: 1px solid #f3f4f6; }}
  .badge {{ display: inline-block; padding: 0.15rem 0.5rem; border-radius: 9999px; font-size: 0.7rem; font-weight: 600; }}
  .badge-green {{ background: #dcfce7; color: var(--green); }}
  .badge-red {{ background: #fee2e2; color: var(--red); }}
  .badge-amber {{ background: #fef3c7; color: var(--amber); }}
  .footer {{ text-align: center; color: var(--gray); font-size: 0.8rem; padding: 2rem; }}
</style>
</head>
<body>
<div class="header">
  <h1>rai-guard Compliance Evidence Report</h1>
  <p>Generated: {generated_at} &nbsp;|&nbsp; Requests analysed: {total_requests} &nbsp;|&nbsp; Report ID: {report_id}</p>
</div>
<div class="container">

  <div class="grid-3">
    <div class="card">
      <h3>OWASP LLM Top 10</h3>
      <div class="value grade-{owasp_grade}">{owasp_score}%</div>
      <p style="color:var(--gray);font-size:.85rem;margin-top:.25rem">Grade {owasp_grade}</p>
    </div>
    <div class="card">
      <h3>EU AI Act Compliance</h3>
      <div class="value grade-{eu_grade}">{eu_score}%</div>
      <p style="color:var(--gray);font-size:.85rem;margin-top:.25rem">Grade {eu_grade}</p>
    </div>
    <div class="card">
      <h3>Requests Blocked</h3>
      <div class="value" style="color:var(--red)">{blocked}</div>
      <p style="color:var(--gray);font-size:.85rem;margin-top:.25rem">Pass rate {pass_rate}%</p>
    </div>
  </div>

  <div class="section">
    <h2>OWASP LLM Top 10 — Category Breakdown</h2>
    <table>
      <thead><tr><th>Category</th><th>Name</th><th>Risk Score</th><th>Status</th></tr></thead>
      <tbody>{owasp_rows}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>EU AI Act — Article Compliance</h2>
    <table>
      <thead><tr><th>Article</th><th>Title</th><th>Score</th><th>Risk Level</th><th>Status</th></tr></thead>
      <tbody>{eu_rows}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>NIST AI RMF — Maturity Levels</h2>
    <table>
      <thead><tr><th>Function</th><th>Description</th><th>Maturity</th></tr></thead>
      <tbody>{nist_rows}</tbody>
    </table>
  </div>

  {recent_incidents_section}

</div>
<div class="footer">
  Generated by <strong>rai-guard</strong> — Runtime Responsible AI Compliance &nbsp;|&nbsp; https://github.com/rai-guard/rai-guard
</div>
</body>
</html>"""


def _badge(text: str, color: str) -> str:
    return f'<span class="badge badge-{color}">{text}</span>'


def generate_json_report(
    owasp_score_data: dict[str, Any],
    owasp_findings: list[Any],
    eu_score_data: dict[str, Any],
    eu_findings: list[Any],
    nist_findings: list[Any],
    store_stats: dict[str, Any] | None = None,
    recent_incidents: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Generate a structured JSON compliance evidence report."""
    return {
        "report_version": "1.0",
        "generator": "rai-guard",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "owasp_llm_top10": owasp_score_data,
            "eu_ai_act": eu_score_data,
            "operational": store_stats or {},
        },
        "owasp_llm_findings": [
            {
                "category_id": f.category_id,
                "category_name": f.category_name,
                "risk_score": f.risk_score,
                "compliant": f.compliant,
                "triggered_checks": f.triggered_by,
                "evidence": f.evidence,
            }
            for f in owasp_findings
        ],
        "eu_ai_act_findings": [
            {
                "article": f.article,
                "title": f.title,
                "compliant": f.compliant,
                "compliance_score": f.compliance_score,
                "risk_level": f.risk_level,
                "evidence_collected": f.evidence_collected,
                "evidence_gaps": f.evidence_gaps,
            }
            for f in eu_findings
        ],
        "nist_ai_rmf_findings": [
            {
                "function": f.function,
                "maturity_level": f.maturity_level,
                "maturity_label": f.maturity_label,
                "subcategory_scores": f.subcategory_scores,
                "recommendations": f.recommendations,
            }
            for f in nist_findings
        ],
        "recent_incidents": recent_incidents or [],
    }


def generate_html_report(
    owasp_score_data: dict[str, Any],
    owasp_findings: list[Any],
    eu_score_data: dict[str, Any],
    eu_findings: list[Any],
    nist_findings: list[Any],
    store_stats: dict[str, Any] | None = None,
    recent_incidents: list[dict[str, Any]] | None = None,
) -> str:
    """Generate a self-contained HTML compliance evidence report."""
    import uuid as _uuid

    stats = store_stats or {}
    total = stats.get("total_requests", 0)
    blocked = stats.get("blocked_requests", 0)
    pass_rate = stats.get("pass_rate", 100.0)

    # OWASP rows
    owasp_rows = ""
    for f in owasp_findings:
        status = _badge("PASS", "green") if f.compliant else _badge("FAIL", "red")
        risk_pct = f"{round(f.risk_score * 100, 1)}%"
        owasp_rows += (
            f"<tr><td><strong>{f.category_id}</strong></td>"
            f"<td>{f.category_name}</td>"
            f"<td>{risk_pct}</td>"
            f"<td>{status}</td></tr>"
        )

    # EU AI Act rows
    eu_rows = ""
    for f in eu_findings:
        status = _badge("COMPLIANT", "green") if f.compliant else _badge("NON-COMPLIANT", "red")
        risk_badge = _badge(f.risk_level.upper(), "red" if f.risk_level in ("critical", "high") else "amber" if f.risk_level == "medium" else "green")
        eu_rows += (
            f"<tr><td><strong>{f.article}</strong></td>"
            f"<td>{f.title}</td>"
            f"<td>{f.compliance_score}%</td>"
            f"<td>{risk_badge}</td>"
            f"<td>{status}</td></tr>"
        )

    # NIST rows
    nist_rows = ""
    for f in nist_findings:
        bar = "█" * f.maturity_level + "░" * (4 - f.maturity_level)
        nist_rows += (
            f"<tr><td><strong>{f.function}</strong></td>"
            f"<td style='font-size:.8rem;color:#6b7280'>{f.description[:80]}...</td>"
            f"<td>{bar} {f.maturity_level}/4 — {f.maturity_label}</td></tr>"
        )

    # Recent incidents
    incident_html = ""
    if recent_incidents:
        rows = ""
        for inc in recent_incidents[:10]:
            ts = inc.get("timestamp", "")[:19].replace("T", " ")
            risk = inc.get("risk_score", 0.0)
            status = _badge("BLOCKED", "red") if not inc.get("passed") else _badge("PASSED", "green")
            rows += f"<tr><td>{ts}</td><td>{inc.get('direction','')}</td><td>{risk:.3f}</td><td>{status}</td></tr>"
        incident_html = f"""
        <div class="section">
          <h2>Recent Incidents</h2>
          <table>
            <thead><tr><th>Timestamp</th><th>Direction</th><th>Risk Score</th><th>Status</th></tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </div>"""

    owasp_grade = owasp_score_data.get("grade", "F")
    eu_grade = eu_score_data.get("grade", "F")

    return _HTML_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        total_requests=total,
        report_id=str(_uuid.uuid4())[:8].upper(),
        owasp_score=owasp_score_data.get("score", 0),
        owasp_grade=owasp_grade,
        eu_score=eu_score_data.get("score", 0),
        eu_grade=eu_grade,
        blocked=blocked,
        pass_rate=pass_rate,
        owasp_rows=owasp_rows,
        eu_rows=eu_rows,
        nist_rows=nist_rows,
        recent_incidents_section=incident_html,
    )


def save_report(
    report_data: dict[str, Any] | str,
    output_path: str | Path,
) -> Path:
    """Save report to file. Accepts dict (saved as JSON) or str (saved as HTML)."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if isinstance(report_data, dict):
        path.write_text(json.dumps(report_data, indent=2), encoding="utf-8")
    else:
        path.write_text(report_data, encoding="utf-8")

    return path
